export enum InventoryErrorCode {
  PRODUCT_UNAVAILABLE = 'PRODUCT_UNAVAILABLE',
  CATALOG_CHANGED = 'CATALOG_CHANGED',
  INSUFFICIENT_STOCK = 'INSUFFICIENT_STOCK',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  RESERVATION_NOT_FOUND = 'RESERVATION_NOT_FOUND',
  RESERVATION_EXPIRED = 'RESERVATION_EXPIRED',
  RESERVATION_NOT_ACTIVE = 'RESERVATION_NOT_ACTIVE',
  RESERVATION_QUANTITY_INVALID = 'RESERVATION_QUANTITY_INVALID',
  PRODUCT_HAS_ACTIVE_RESERVATIONS = 'PRODUCT_HAS_ACTIVE_RESERVATIONS',
  INVENTORY_CONFLICT = 'INVENTORY_CONFLICT',
}

export class InventoryError extends Error {
  constructor(
    readonly code: InventoryErrorCode,
    message: string = code,
  ) {
    super(message);
    this.name = 'InventoryError';
  }
}
